name: MacOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CTEST_OUTPUT_ON_FAILURE: 1

jobs:
  build:
    runs-on: macos-10.15
    strategy:
      matrix:
        config: [Debug, Release]

    steps:
      - uses: actions/checkout@v2
      - uses: turtlebrowser/get-conan@v1.0

      - name: install conan dependencies
        run: conan install -if build .

      - name: configure
        run: cmake . -Bbuild -DCMAKE_BUILD_TYPE=${{ matrix.config }}

      - name: build
        run: cmake --build build -j4

      - name: test
        run: |
          cd build
          ctest --build-config ${{ matrix.config }}
