name: Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CTEST_OUTPUT_ON_FAILURE: 1

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        config: [Debug, Release]

    steps:
      - uses: actions/checkout@v2
      - uses: turtlebrowser/get-conan@v1.0

      - name: install conan dependencies
        run: conan install -if build -s build_type=${{ matrix.config }} .

      - name: configure
        run: cmake . -Bbuild

      - name: build
        run: cmake --build build --config ${{ matrix.config }} -j4

      - name: test
        run: |
          cd build
          ctest --build-config ${{ matrix.config }}
